### ISSUE TITLE
exception: disposed with an active ticker

### ISSUE THREAD

**Issue by modulovalue** [Norbert515/pimp_my_button#2]
relevant lines
```
The following assertion was thrown while finalizing the widget tree:
flutter: PimpedButtonState#0c8cd(ticker active) was disposed with an active Ticker.
flutter: PimpedButtonState created a Ticker via its SingleTickerProviderStateMixin, but at the time dispose()
flutter: was called on the mixin, that Ticker was still active. The Ticker must be disposed before calling
flutter: super.dispose(). Tickers used by AnimationControllers should be disposed by calling dispose() on the
flutter: AnimationController itself. Otherwise, the ticker will leak.
flutter: The offending ticker was: Ticker(created by PimpedButtonState#0c8cd(lifecycle state: created))
flutter: The stack trace when the Ticker was actually created was:
...
flutter: #4      PimpedButtonState.initState (package:pimp_my_button/src/pimp_my_button.dart:38:18)
```

full stacktrace:
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while finalizing the widget tree:
flutter: PimpedButtonState#0c8cd(ticker active) was disposed with an active Ticker.
flutter: PimpedButtonState created a Ticker via its SingleTickerProviderStateMixin, but at the time dispose()
flutter: was called on the mixin, that Ticker was still active. The Ticker must be disposed before calling
flutter: super.dispose(). Tickers used by AnimationControllers should be disposed by calling dispose() on the
flutter: AnimationController itself. Otherwise, the ticker will leak.
flutter: The offending ticker was: Ticker(created by PimpedButtonState#0c8cd(lifecycle state: created))
flutter: The stack trace when the Ticker was actually created was:
flutter: #0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:64:40)
flutter: #1      new Ticker (package:flutter/src/scheduler/ticker.dart:66:6)
flutter: #2      _PimpedButtonState&State&SingleTickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:97:19)
flutter: #3      new AnimationController (package:flutter/src/animation/animation_controller.dart:155:21)
flutter: #4      PimpedButtonState.initState (package:pimp_my_button/src/pimp_my_button.dart:38:18)
flutter: #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3763:58)
flutter: #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #8      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4771:32)
flutter: #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #23     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
flutter: #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
flutter: #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
flutter: #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #50     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
flutter: #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #57     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
flutter: #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #68     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3967:11)
flutter: #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #70     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4771:32)
flutter: #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #73     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #79     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
flutter: #80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #83     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #85     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4771:32)
flutter: #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #97     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
flutter: #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #101    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #110    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #116    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
flutter: #117    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #122    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #123    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
flutter: #124    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #125    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #127    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #130    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #134    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #135    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #136    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
flutter: #137    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #138    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #139    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #141    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #142    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #143    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #144    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #145    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #146    _SliverPersistentHeaderElement._build.<anonymous closure> (package:flutter/src/widgets/sliver_persistent_header.dart:199:15)
flutter: #147    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
flutter: #148    _SliverPersistentHeaderElement._build (package:flutter/src/widgets/sliver_persistent_header.dart:198:11)
flutter: #149    __RenderSliverPinnedPersistentHeaderForWidgets&_RenderSliverPinnedPersistentHeader&_RenderSliverPersistentHeaderForWidgetsMixin.updateChild (package:flutter/src/widgets/sliver_persistent_header.dart:270:14)
flutter: #150    RenderSliverPersistentHeader.layoutChild.<anonymous closure> (package:flutter/src/rendering/sliver_persistent_header.dart:126:9)
flutter: #151    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1727:58)
flutter: #152    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
flutter: #153    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1727:13)
flutter: #154    RenderSliverPersistentHeader.layoutChild (package:flutter/src/rendering/sliver_persistent_header.dart:124:7)
flutter: #155    RenderSliverPinnedPersistentHeader.performLayout (package:flutter/src/rendering/sliver_persistent_header.dart:294:5)
flutter: #156    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #157    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
flutter: #158    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1320:12)
flutter: #159    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1238:20)
flutter: #160    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #161    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #162    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #163    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #164    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #165    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #166    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #167    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #168    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #169    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #170    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #171    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
flutter: #172    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
flutter: #173    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
flutter: #174    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
flutter: #175    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #176    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #177    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #178    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #179    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1192:11)
flutter: #180    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #181    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #182    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #183    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #184    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #185    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #186    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #187    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
flutter: #188    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #189    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #190    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #191    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #192    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #193    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #194    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #195    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #196    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #197    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #198    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #199    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2882:14)
flutter: #200    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #201    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
flutter: #202    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #203    __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #204    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #205    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #206    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #207    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #208    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #209    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #210    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #211    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
flutter: #212    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #213    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #214    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #215    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #216    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #217    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #218    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #219    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #220    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #221    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
flutter: #222    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
flutter: #223    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
flutter: #224    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
flutter: #225    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
flutter: #226    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
flutter: #227    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1506:7)
flutter: #228    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
flutter: #229    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
flutter: #230    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
flutter: #231    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #232    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #233    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #234    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #235    _invoke (dart:ui/hooks.dart:128:13)
flutter: #236    _drawFrame (dart:ui/hooks.dart:117:3)
```

and 

```
flutter: When the exception was thrown, this was the stack:
flutter: #0      _PimpedButtonState&State&SingleTickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:110:7)
flutter: #1      _PimpedButtonState&State&SingleTickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:119:6)
flutter: #2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3833:12)
flutter: #3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1697:13)
flutter: #4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #5      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4754:16)
flutter: #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #8      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #11     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
...
```

**Comment by mgleason** [comment]
Calling `super.dispose()` ahead of `_controller.dispose()` caused this error in my project. 

Swapping it so that `_controller.dispose()` was called first fixed it:
```dart
@override
void dispose() {
  _controller.dispose();
  super.dispose();
}
```

**Comment by russomaclaud** [comment]
Excelente muchas gracias
